name: New lab project nomination
description: Nomination for OSCAL Compass Lab project establishment
title: 'New Lab project'
labels: ["nomination"]
assignees:
  - community-maintainers
body:
  - type: input
    id: project-name
    attributes:
      label: Project Name
      placeholder: e.g., Super cool OSCAL Compass Lab project name
    validations:
      required: true
  - type: input
    id: project-description
    attributes:
      label: Project Description
      placeholder: e.g., Super cool OSCAL Compass Lab project description
    validations:
      required: true
  - type: input
    id: proposed-repo-name
    attributes:
      label: Proposed Repository Name
      placeholder: e.g., super-cool-oscal-compass-addition
    validations:
      required: true
  - type: input
    id: project-repo-url
    attributes:
      label: Current Repository URL
      description: If this is a transfer of an existing project, specify the current repository URL. Otherwise specify N/A.
      placeholder: e.g., https://github.com/dontation-org/donation-project
    validations:
      required: true      
      
      
      