name: New lab project nomination
description: Nomination for OSCAL Compass Lab project establishment
title: 'New Lab project'
labels: ["nomination"]
assignees:
  - community-maintainers
body:
      
  - type: input
    id: project-name
    attributes:
      label: Project Name
      placeholder: e.g., Super cool OSCAL Compass addition
    validations:
      required: true
      
  - type: markdown
    id: project-description
    attributes:
      label: Project Description
      description: Briefly describe the purpose and goals of this new project.
      placeholder: What problem does this project solve? What are its key features? How does it relate to and/or benefit OSCAL Compass?
    validations:
      required: true